name: todoey
description: "A todo app."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  rflutter_alert: ^2.0.7
  flutter_expandable_fab: ^2.3.0
  flutter_speed_dial: ^7.0.0
  sqflite: ^2.3.3+2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true